---
name: Nightly Rebuild for rpmc-git
on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"
    
jobs:
  rebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Get sha for HEAD of master at rmpc
        env:
          OWNER: mierak
          REPO: rmpc
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${OWNER}/${REPO}/commits?per_page=1 \
            | jq '.[0].sha' | cut -c1-7 > RMPC_HEAD_SHA
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: updating rmpc HEAD commit sha
